### ISSUE TITLE
previous_level never updated?

### ISSUE THREAD

**Issue by potentcocktail** [jedisct1/libpuzzle#12]
Just browsing the source for dvec.c, in puzzle_autocrop_axis() it seems that previous_level is initialized to zero but never updated. Shouldn't it be updated each time through the inner do loop and then reset afterward? The way it is now, it seems that the chunk_contrast calculation is terribly off...

**Comment by jedisct1** [comment]
Good catch. Indeed, `previous_level` should definitely be updated or it kinda defeats the whole point of the function.

Thanks for spotting this old standing bug!

It should be fixed now.

Thanks again!

**Comment by potentcocktail** [comment]
No problem! Glad to help!
