### ISSUE TITLE
IndexError for Ruby FFI wrapper

### ISSUE THREAD

**Issue by neezer** [jedisct1/libpuzzle#5]
I'm trying to write a [Ruby FFI](https://github.com/ffi/ffi) wrapper around `libpuzzle`, which you can find here: https://github.com/neezer/ffi-libpuzzle

I'm just trying to get a cvec vector (compressed or uncompressed) for an image, to persist in my database, using the wrapper above like this:

```ruby
require 'ffi-libpuzzle'
file_path = File.expand_path(File.dirname(__FILE__), 'test/fixtures/test.jpg')
s = Puzzle.new file_path
s.cvec_sig
```

Which results in this error:

```
Memory access offset=8 size=1 is out of bounds (IndexError)
```

I think I have the C struct correctly mirrored in FFI, in `lib/ffi-libpuzzle/libpuzzle.rb`, but I'm really new to this and don't know C really well. Anyone have any insights as to what I'm doing wrong here?

NOTE: I know that this issue isn't about `libpuzzle` directly, but I figured that there would be other more knowledgable folk than I who might know how to make this work, so I figured it was worth posting here.

**Comment by tonytonyjan** [comment]
@neezer Hey, I just wrote a [similar gem](https://github.com/tonytonyjan/libpuzzle_ruby) like yours, and after that I found your gem through this issue. XD
 
It's happy to see there is more than one option to use libpuzzle in Ruby! However it seems that your link is dead, I wonder if you are still working on it?

**Comment by neezer** [comment]
Nah, stopped that a while ago. Had a working implementation [in javascript](https://github.com/neezer/puzzle.js) though, but more as an experiment than anything ready for a prod-like environment. Good luck, though!

**Comment by tonytonyjan** [comment]
@neezer Good luck :+1:
