### ISSUE TITLE
Transparency is not taken into account

### ISSUE THREAD

**Issue by Benny-** [jedisct1/libpuzzle#9]
I use `puzzle-diff -e -E 0 input.png output.png` for all images here.

Some equal images are incorrectly marked unequal.
Some unequal images are incorrectly marked equal.

The following images are not equal according to puzzle-diff:
![Applebloom and Babs Seed](http://bennyjacobs.nl/issues/libpuzzle/abandbabs.png)
![Applebloom, Babs Seed and a hidden demon](http://bennyjacobs.nl/issues/libpuzzle/abandbabs_hidden_demon.png)

The following images are equal according to puzzle-diff:
![Applebloom and Babs Seed](http://bennyjacobs.nl/issues/libpuzzle/abandbabs.png)
![Only Babs Seed](http://bennyjacobs.nl/issues/libpuzzle/noab.png)
![Only Applebloom](http://bennyjacobs.nl/issues/libpuzzle/nobab.png)

The following images are equal according to puzzle-diff:
![disciplinarykill](http://bennyjacobs.nl/issues/libpuzzle/disciplinarykill.png)
![revolverkill](http://bennyjacobs.nl/issues/libpuzzle/revolverkill.png)
![disciplinarykill.alphaless](http://bennyjacobs.nl/issues/libpuzzle/disciplinarykill.alphaless.png)
![caberkill](http://bennyjacobs.nl/issues/libpuzzle/caberkill.png)

Everything here has to do with transparency. Fully transparent pixels can still have colors, libpuzzle incorrectly takes these invisible colors into account.

You can see the colors by removing the alpha using image-magick:

``` bash
convert "./input.png" -alpha off "./alphaless.png"
```

**Comment by ifsnop** [comment]
This fix looks ok to me, any hope that will be merged?

**Comment by Benny-** [comment]
This pull request was merged 2 hours ago. Thanks!
